### ISSUE TITLE
Spin an IconDrawable

### ISSUE THREAD

**Issue by JoanZapata** [JoanZapata/android-iconify#107]
See #56:

@guilhermesgb Is it possible to make an IconDrawable spin (programatically)?

> @joanzapata Spin only works in IconTextView, IconButton and IconToggleButton for now.
I guess it wouldn't be very complicated to make a SpinningIconDrawable, but I'm concerned about memory leaks: I'm not sure a Drawable can know when it's not displayed anymore, so the refresh-loop wouldn't know when to stop. Could be based on the context, but that's not accurate. I'll see what I can do.

**Comment by guilhermesgb** [comment]
I still think this would be useful (as in convenient) but definitely something that we can live by without.

+1

**Comment by ch-muhammad-adil** [comment]
I am using IconTextView

< com.joanzapata.iconify.widget.IconTextView
...
android:text="{fa-cog spin}" 
.../>

spin isn't working . :(

**Comment by JoanZapata** [comment]
@ch-muhammad-adil It has nothing to do with `IconDrawable`. Please open a separate issue and specify which version of Iconify you're using.

**Comment by JoanZapata** [comment]
This won't be fixed, as discussed in #56, a drawable can be used in many ways and spinning requires to regularly invalidate the drawable **until the target view is detached**. Detecting the fact that the view is detached is difficult and any mistake would create a memory leak. 

**Workarounds**
Consider using an `IconTextView`. If used on `ImageView`, use an animation to rotate the `ImageView`. If used elsewhere or rendered directly, progressively rotate the `Canvas` before drawing the `Drawable` would achieve the spinning effect.

**Comment by ch-muhammad-adil** [comment]
ok thank you . I will manage it.

Regards,
Muhammad Adil

**Comment by 1zaman** [comment]
@JoanZapata: Drawable animations don't leak anything, because it depends on the `draw()` callback instead of using a global scheduler (just like view animations). If a view is detached then it's no longer being drawn, and thus all it's animation cycle is automatically stopped (including drawables).

For an example of drawable rotate animation, you can check out the hidden [AnimatedRotateDrawable][] implementation from the framework.

[AnimatedRotateDrawable]: https://android.googlesource.com/platform/frameworks/base/+/master/graphics/java/android/graphics/drawable/AnimatedRotateDrawable.java

**Comment by 1zaman** [comment]
I added support for spin animation in `IconDrawable` in #134.
