### ISSUE TITLE
android:textAllCaps="true" causing icons not to display

### ISSUE THREAD

**Issue by fredszaq** [JoanZapata/android-iconify#124]
When adding `android:textAllCaps="true"` to a text view with icons, the icons are not displayed, a stroked square or nothing at all is displayed depending on the device used

**Comment by pinfrederic** [comment]
I need a fix too...

**Comment by JoanZapata** [comment]
It's actually a incompatibility between textAllCaps and spans. 
See https://code.google.com/p/android/issues/detail?id=67509

I'm not sure what I should do about it : 
* Add a custom attribute `allCaps` usable on `IconTextView`, `IconButton`, etc.. instead of the original one. That would still break integration with other libraries that use `Spans`.
* Allow you to easily uppercase your texts using `textView.setText("hello {icon}".toUpperCase())` without breaking Iconify, by doing `toLowerCase` on icon keys internally. But that means icon keys would become case-independant, which is a (minor) breaking change.
* Nothing

@fredszaq @pinfrederic WDYT?

**Comment by JoanZapata** [comment]
Well I think I'll take the third option after all, there's no _good_ way to solve this.

**Comment by fredszaq** [comment]
It seems to be the best option yes !

**Comment by jlhonora** [comment]
Obviously this is your own project and I respect every decision you make about it, but when this bug bites you it bites you hard. At least for me this is a deal breaker.

Making icon keys case insensitive doesn't seem to be too bad an option in my opinion. Perhaps you can think about it :) ?
