### ISSUE TITLE
Render icons in preview mode in Android Studio

### ISSUE THREAD

**Issue by Dj-jom2x** [JoanZapata/android-iconify#152]
hmmm is it posible to render it on display ? 

when you put 
android:text="{fa-envelope-o 19dp}" 

it will only render on phone :(  but not on preview

because i need to run and run to check if icons are perfectly align  ..

**Comment by JoanZapata** [comment]
It would be a nice thing to have. Unfortunately I think it would be very complex.
* During the preview, which is run on your computer, the font is not loaded. It would need to find on your FS and parse it in this case.
* I don't know if `Span`s are supported in preview mode.

**Comment by 1zaman** [comment]
There are two reasons why this doesn't work:

1. The preview doesn't load assets from library projects.
2. The font modules need to be registered so that the widget can find the icon. Usually, this is done at application initialization time, but those callbacks are not invoked by the preview.

I worked around these issues in the edX project thus:

1. Added the TTF file for my font in my project's assets at the same path as in the font module, and with the same name.
2. Extend all the icon widget classes, add a static initializer in them which registers my font modules, and use those classes in XML layout definitions (e.g. [IconTextViewXml][]).

[IconTextViewXml]: https://github.com/edx/edx-app-android/blob/1f35f810e456bc1ca04a6f95d80df4dd317aea00/VideoLocker/src/main/java/org/edx/mobile/view/custom/IconTextViewXml.java

**Comment by JoanZapata** [comment]
@1zaman I'm sorry to hear that, it looks like a painful process. 

Unfortunately I don't think that can be provided by the lib, so I'm closing this issue. Hopefully @Dj-jom2x you can now test a lot more faster with `Instant Run`.

**Comment by 1zaman** [comment]
Yeah, the second issue could be solved by having the font module classes registered statically in a properties file which is read from a static initializer in the `Iconify` class, but the first issue can't be solved from the library itself. I have logged a bug report on it at http://b.android.com/202208. Hopefully, it will be fixed in a future version of Studio, at which point this ticket might be reopened.
