### ISSUE TITLE
Support for spinning icons?

### ISSUE THREAD

**Issue by rampatra** [JoanZapata/android-iconify#56]
I was wondering how do i use <a href="http://fortawesome.github.io/Font-Awesome/examples/#spinning">spinning icons</a>.

I tried with `{fa-spinner fa-spin}` and `{fa-spinner} {fa-spin}` but none of them worked.

So, am I going wrong somewhere or iconify doesn't support spinning icons?

**Comment by guilhermesgb** [comment]
So it seems it eventually got implemented (as per the README.md).
So I was wondering: Is it possible to make an IconDrawable spin (programatically)?

**Comment by JoanZapata** [comment]
Spin only works in `IconTextView`, `IconButton` and `IconToggleButton` for now.

I guess it wouldn't be very complicated to make a `SpinningIconDrawable`, but I'm concerned about memory leaks: I'm not sure a `Drawable` can know when it's not displayed anymore, so the refresh-loop wouldn't know when to stop. Could be based on the context, but that's not accurate. I'll see what I can do.

I'm opening a new issue for this.

**Comment by guilhermesgb** [comment]
That's great, man. And thanks for the response!

I don't really know the inner workings of rendering drawables, but maybe there's another approach that could work. If there's a way to force a drawable to be rendered continuously while it is within viewport bounds, maybe you could keep state on it's current rotation and on every draw step, increase it just a bit before rendering it. Then I'd try evolving from there (so that the rotation is smooth / not dependent on the "clock"/draw steps / happening at a stable pace).

**Comment by JoanZapata** [comment]
That's actually how `{fa-cog spin}` works inside a `IconTextView`. It's continuously invalidated and redrawn, and stops when the `IconTextView` is detached from the window. 

But I don't think there's a way to know when a `Drawable` is not anymore displayed on the screen, so there's no way no know when to stop continuously rendering it. If it's attached to an `ImageView` then it depends on this `ImageView`, but a `Drawable` can be used (and reused) in many other ways. 

What is **your** usecase? `ImageView`?

**Comment by guilhermesgb** [comment]
I understand… thanks. Yeah, it's tricky if it depends heavily on where the
Drawable's used.
I'm using it alongside/attached to an `EditText`, as its `drawableEnd`
drawable.

**Comment by JoanZapata** [comment]
Can't you just use `IconEditText` and put `{fa-something spin}` at the end of the text?

**Comment by guilhermesgb** [comment]
Yeah, that's the other approach I considered taking but was too lazy to go ahead and build it myself last night, as I think I'd have to perform a major copy-and-pasting of the `EditText`'s source and have this new class it extend `IconTextView`, I really couldn`t think of a better approach.

(And I actually don't *need* a spinning IconDrawable - I'm just experimenting with this library to see how powerful it just for curiosity's sake right now, I plan on using it in future projects.)

**Comment by JoanZapata** [comment]
Oh my bad, I just realized you were talking about an `EditText` and not a `TextView`!
There's actually a convenient lib based on Iconify which does just that!
https://github.com/DayS/EnhancedEditText/

**Comment by guilhermesgb** [comment]
That's cool, and thanks for referring me to that library! In the meanwhile I attempted building `IconEditText`.  That approach I mentioned above works great unless you want to apply icons to `hint`'s as well (my case). Unfortunatelly `setHint` is final and thus cannot be overriden.

I need that because I want to use `EditText` in conjunction with `TextInputLayout`. Apparently it's not supported by [EnhancedEditText](https://github.com/DayS/EnhancedEditText/) as well, at least from what I could tell by quickly skimming through the source. So that's potentially a cool PR I could try sending them, thanks! :)

**Comment by ch-muhammad-adil** [comment]
I am using IconTextView

<com.joanzapata.iconify.widget.IconTextView
        android:text="{fa-cog spin}" 
.../>

spin isn't working . :(

**Comment by fxpage** [comment]
@JoanZapata can I change spinning speed?
